import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ServiceWorkerRegistrar } from "@/components/ServiceWorkerRegistrar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/**
 * 2026 PWA Metadata
 * This replaces the old <link> tags in the head.
 * The 'manifest' property automatically links to your app/manifest.ts
 */
export const metadata: Metadata = {
  title: "Viralook AI Studio | AI Summoning Suite",
  description: "The ultimate AI summoning suite for viral creators. Manifest your vision in seconds.",
  manifest: "/manifest.webmanifest", // Generated by manifest.ts
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: "Viralook AI",
  },
};

/**
 * Modern Next.js 15+ Viewport Config
 * Ensures the app looks like a native "Viralook" app (no zooming, neon theme).
 */
export const viewport: Viewport = {
  themeColor: "#000000",
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white selection:bg-cyan-500/30`}
      >
        {/* The bridge between the browser and your background service worker */}
        <ServiceWorkerRegistrar />
        
        {/* Main Application Container */}
        <div className="relative min-h-screen overflow-x-hidden">
          {/* Subtle Global Neon Backdrop */}
          <div className="fixed inset-0 bg-[radial-gradient(circle_at_50%_50%,#161616_0%,#000000_100%)] -z-10" />
          
          {children}
        </div>
      </body>
    </html>
  );
}

